name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches: [v4]
  workflow_dispatch:
  repository_dispatch:
    types: [vault-updated]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Pull your vault repo
      - name: Checkout vault content
        uses: actions/checkout@v4
        with:
          repository: Devansh-Mahajan/My-Website
          ref: main
          path: vault

      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci

      # Debug: show vault structure
      - name: Show vault files (debug)
        run: |
          echo "Vault tree (top level):"
          ls -la ./vault | head -n 200

      # Sync vault into Quartz's content dir
      - name: Sync vault -> content
        run: |
          rm -rf content/*
          rsync -av --delete --exclude ".git/" ./vault/ ./content/

      # Debug: confirm content populated
      - name: Show content after sync (debug)
        run: |
          echo "Content tree after sync:"
          ls -la ./content | head -n 200

      - name: Build Quartz
        run: npx quartz build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
